const { withAndroidManifest } = require('@expo/config-plugins');

/**
 * Force MainActivity to launchMode="singleTop" for Google Play Billing.
 *
 * Expo prebuild defaults MainActivity to "singleTask", but RevenueCat's React
 * Native setup requires "standard" or "singleTop": with "singleTask", returning
 * from an external payment flow can recreate the activity and drop the purchase
 * callback, so Play charges the user while the app never grants the entitlement.
 *
 * This matters more here than in most apps because M-Pesa — the main payment
 * rail for our Kenyan users — backgrounds the app for PIN confirmation on every
 * purchase, which is exactly the case the warning describes.
 *
 * Lives as a plugin rather than a manifest edit because android/ is gitignored
 * and regenerated by `expo prebuild`.
 *
 * @see https://www.revenuecat.com/docs/getting-started/installation/reactnative
 */
module.exports = function withPurchasesLaunchMode(config) {
  return withAndroidManifest(config, (cfg) => {
    const activity = cfg.modResults.manifest.application?.[0]?.activity?.find(
      (a) => a.$['android:name'] === '.MainActivity'
    );
    if (!activity) {
      throw new Error(
        'withPurchasesLaunchMode: .MainActivity not found in AndroidManifest — ' +
          'purchases would silently break, so failing the build instead.'
      );
    }
    activity.$['android:launchMode'] = 'singleTop';
    return cfg;
  });
};
