// GENERATED by scripts/generate-verse-data.mjs — do not hand-edit verse text.
// Source: bible-api.com (World English Bible + King James Version, public domain).

export type Translation = 'WEB' | 'KJV';

export interface BundledVerse {
  id: string;
  reference: string;
  text: Record<Translation, string>;
}

export const VERSES: BundledVerse[] = [
  {
    "id": "john-3-16",
    "reference": "John 3:16",
    "text": {
      "WEB": "For God so loved the world, that he gave his one and only Son, that whoever believes in him should not perish, but have eternal life.",
      "KJV": "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life."
    }
  },
  {
    "id": "jeremiah-29-11",
    "reference": "Jeremiah 29:11",
    "text": {
      "WEB": "For I know the thoughts that I think toward you,” says Yahweh, “thoughts of peace, and not of evil, to give you hope and a future.",
      "KJV": "For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end."
    }
  },
  {
    "id": "philippians-4-13",
    "reference": "Philippians 4:13",
    "text": {
      "WEB": "I can do all things through Christ, who strengthens me.",
      "KJV": "I can do all things through Christ which strengtheneth me."
    }
  },
  {
    "id": "psalm-23-1",
    "reference": "Psalm 23:1",
    "text": {
      "WEB": "Yahweh is my shepherd: I shall lack nothing.",
      "KJV": "The LORD is my shepherd; I shall not want."
    }
  },
  {
    "id": "proverbs-3-5-6",
    "reference": "Proverbs 3:5-6",
    "text": {
      "WEB": "Trust in Yahweh with all your heart, and don’t lean on your own understanding. In all your ways acknowledge him, and he will make your paths straight.",
      "KJV": "Trust in the LORD with all thine heart; and lean not unto thine own understanding. In all thy ways acknowledge him, and he shall direct thy paths."
    }
  },
  {
    "id": "romans-8-28",
    "reference": "Romans 8:28",
    "text": {
      "WEB": "We know that all things work together for good for those who love God, to those who are called according to his purpose.",
      "KJV": "And we know that all things work together for good to them that love God, to them who are the called according to his purpose."
    }
  },
  {
    "id": "isaiah-41-10",
    "reference": "Isaiah 41:10",
    "text": {
      "WEB": "Don’t you be afraid, for I am with you. Don’t be dismayed, for I am your God. I will strengthen you. Yes, I will help you. Yes, I will uphold you with the right hand of my righteousness.",
      "KJV": "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness."
    }
  },
  {
    "id": "matthew-6-33",
    "reference": "Matthew 6:33",
    "text": {
      "WEB": "But seek first God’s Kingdom, and his righteousness; and all these things will be given to you as well.",
      "KJV": "But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you."
    }
  },
  {
    "id": "joshua-1-9",
    "reference": "Joshua 1:9",
    "text": {
      "WEB": "Haven’t I commanded you? Be strong and courageous. Don’t be afraid. Don’t be dismayed, for Yahweh your God is with you wherever you go.”",
      "KJV": "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest."
    }
  },
  {
    "id": "psalm-46-1",
    "reference": "Psalm 46:1",
    "text": {
      "WEB": "God is our refuge and strength, a very present help in trouble.",
      "KJV": "God is our refuge and strength, a very present help in trouble."
    }
  },
  {
    "id": "galatians-5-22-23",
    "reference": "Galatians 5:22-23",
    "text": {
      "WEB": "But the fruit of the Spirit is love, joy, peace, patience, kindness, goodness, faith, gentleness, and self-control. Against such things there is no law.",
      "KJV": "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, Meekness, temperance: against such there is no law."
    }
  },
  {
    "id": "hebrews-11-1",
    "reference": "Hebrews 11:1",
    "text": {
      "WEB": "Now faith is assurance of things hoped for, proof of things not seen.",
      "KJV": "Now faith is the substance of things hoped for, the evidence of things not seen."
    }
  },
  {
    "id": "2-timothy-1-7",
    "reference": "2 Timothy 1:7",
    "text": {
      "WEB": "For God didn’t give us a spirit of fear, but of power, love, and self-control.",
      "KJV": "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind."
    }
  },
  {
    "id": "psalm-119-105",
    "reference": "Psalm 119:105",
    "text": {
      "WEB": "Your word is a lamp to my feet, and a light for my path.",
      "KJV": "Thy word is a lamp unto my feet, and a light unto my path."
    }
  },
  {
    "id": "romans-12-2",
    "reference": "Romans 12:2",
    "text": {
      "WEB": "Don’t be conformed to this world, but be transformed by the renewing of your mind, so that you may prove what is the good, well-pleasing, and perfect will of God.",
      "KJV": "And be not conformed to this world: but be ye transformed by the renewing of your mind, that ye may prove what is that good, and acceptable, and perfect, will of God."
    }
  },
  {
    "id": "1-corinthians-10-13",
    "reference": "1 Corinthians 10:13",
    "text": {
      "WEB": "No temptation has taken you except what is common to man. God is faithful, who will not allow you to be tempted above what you are able, but will with the temptation also make the way of escape, that you may be able to endure it.",
      "KJV": "There hath no temptation taken you but such as is common to man: but God is faithful, who will not suffer you to be tempted above that ye are able; but will with the temptation also make a way to escape, that ye may be able to bear it."
    }
  },
  {
    "id": "philippians-4-6-7",
    "reference": "Philippians 4:6-7",
    "text": {
      "WEB": "In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus.",
      "KJV": "Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known unto God. And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus."
    }
  },
  {
    "id": "matthew-11-28",
    "reference": "Matthew 11:28",
    "text": {
      "WEB": "“Come to me, all you who labor and are heavily burdened, and I will give you rest.",
      "KJV": "Come unto me, all ye that labour and are heavy laden, and I will give you rest."
    }
  },
  {
    "id": "isaiah-40-31",
    "reference": "Isaiah 40:31",
    "text": {
      "WEB": "But those who wait for Yahweh will renew their strength. They will mount up with wings like eagles. They will run, and not be weary. They will walk, and not faint.",
      "KJV": "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint."
    }
  },
  {
    "id": "psalm-37-4",
    "reference": "Psalm 37:4",
    "text": {
      "WEB": "Also delight yourself in Yahweh, and he will give you the desires of your heart.",
      "KJV": "Delight thyself also in the LORD; and he shall give thee the desires of thine heart."
    }
  },
  {
    "id": "john-14-6",
    "reference": "John 14:6",
    "text": {
      "WEB": "Jesus said to him, “I am the way, the truth, and the life. No one comes to the Father, except through me.",
      "KJV": "Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me."
    }
  },
  {
    "id": "romans-10-9",
    "reference": "Romans 10:9",
    "text": {
      "WEB": "that if you will confess with your mouth that Jesus is Lord, and believe in your heart that God raised him from the dead, you will be saved.",
      "KJV": "That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be saved."
    }
  },
  {
    "id": "ephesians-2-8-9",
    "reference": "Ephesians 2:8-9",
    "text": {
      "WEB": "for by grace you have been saved through faith, and that not of yourselves; it is the gift of God, not of works, that no one would boast.",
      "KJV": "For by grace are ye saved through faith; and that not of yourselves: it is the gift of God: Not of works, lest any man should boast."
    }
  },
  {
    "id": "2-corinthians-5-17",
    "reference": "2 Corinthians 5:17",
    "text": {
      "WEB": "Therefore if anyone is in Christ, he is a new creation. The old things have passed away. Behold, all things have become new.",
      "KJV": "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new."
    }
  },
  {
    "id": "psalm-27-1",
    "reference": "Psalm 27:1",
    "text": {
      "WEB": "Yahweh is my light and my salvation. Whom shall I fear? Yahweh is the strength of my life. Of whom shall I be afraid?",
      "KJV": "The LORD is my light and my salvation; whom shall I fear? the LORD is the strength of my life; of whom shall I be afraid?"
    }
  },
  {
    "id": "proverbs-18-10",
    "reference": "Proverbs 18:10",
    "text": {
      "WEB": "Yahweh’s name is a strong tower: the righteous run to him, and are safe.",
      "KJV": "The name of the LORD is a strong tower: the righteous runneth into it, and is safe."
    }
  },
  {
    "id": "john-8-32",
    "reference": "John 8:32",
    "text": {
      "WEB": "You will know the truth, and the truth will make you free.”",
      "KJV": "And ye shall know the truth, and the truth shall make you free."
    }
  },
  {
    "id": "colossians-3-23",
    "reference": "Colossians 3:23",
    "text": {
      "WEB": "And whatever you do, work heartily, as for the Lord, and not for men,",
      "KJV": "And whatsoever ye do, do it heartily, as to the Lord, and not unto men;"
    }
  },
  {
    "id": "1-peter-5-7",
    "reference": "1 Peter 5:7",
    "text": {
      "WEB": "casting all your worries on him, because he cares for you.",
      "KJV": "Casting all your care upon him; for he careth for you."
    }
  },
  {
    "id": "james-1-5",
    "reference": "James 1:5",
    "text": {
      "WEB": "But if any of you lacks wisdom, let him ask of God, who gives to all liberally and without reproach; and it will be given to him.",
      "KJV": "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him."
    }
  },
  {
    "id": "psalm-34-8",
    "reference": "Psalm 34:8",
    "text": {
      "WEB": "Oh taste and see that Yahweh is good. Blessed is the man who takes refuge in him.",
      "KJV": "O taste and see that the LORD is good: blessed is the man that trusteth in him."
    }
  },
  {
    "id": "matthew-5-16",
    "reference": "Matthew 5:16",
    "text": {
      "WEB": "Even so, let your light shine before men; that they may see your good works, and glorify your Father who is in heaven.",
      "KJV": "Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven."
    }
  },
  {
    "id": "romans-5-8",
    "reference": "Romans 5:8",
    "text": {
      "WEB": "But God commends his own love toward us, in that while we were yet sinners, Christ died for us.",
      "KJV": "But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us."
    }
  },
  {
    "id": "john-1-1",
    "reference": "John 1:1",
    "text": {
      "WEB": "In the beginning was the Word, and the Word was with God, and the Word was God.",
      "KJV": "In the beginning was the Word, and the Word was with God, and the Word was God."
    }
  },
  {
    "id": "genesis-1-1",
    "reference": "Genesis 1:1",
    "text": {
      "WEB": "In the beginning, God created the heavens and the earth.",
      "KJV": "In the beginning God created the heaven and the earth."
    }
  },
  {
    "id": "psalm-139-14",
    "reference": "Psalm 139:14",
    "text": {
      "WEB": "I will give thanks to you, for I am fearfully and wonderfully made. Your works are wonderful. My soul knows that very well.",
      "KJV": "I will praise thee; for I am fearfully and wonderfully made: marvellous are thy works; and that my soul knoweth right well."
    }
  },
  {
    "id": "isaiah-53-5",
    "reference": "Isaiah 53:5",
    "text": {
      "WEB": "But he was pierced for our transgressions. He was crushed for our iniquities. The punishment that brought our peace was on him; and by his wounds we are healed.",
      "KJV": "But he was wounded for our transgressions, he was bruised for our iniquities: the chastisement of our peace was upon him; and with his stripes we are healed."
    }
  },
  {
    "id": "micah-6-8",
    "reference": "Micah 6:8",
    "text": {
      "WEB": "He has shown you, O man, what is good. What does Yahweh require of you, but to act justly, to love mercy, and to walk humbly with your God?",
      "KJV": "He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?"
    }
  },
  {
    "id": "matthew-28-19-20",
    "reference": "Matthew 28:19-20",
    "text": {
      "WEB": "Go and make disciples of all nations, baptizing them in the name of the Father and of the Son and of the Holy Spirit, teaching them to observe all things that I commanded you. Behold, I am with you always, even to the end of the age.” Amen.",
      "KJV": "Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost: Teaching them to observe all things whatsoever I have commanded you: and, lo, I am with you alway, even unto the end of the world. Amen."
    }
  },
  {
    "id": "acts-1-8",
    "reference": "Acts 1:8",
    "text": {
      "WEB": "But you will receive power when the Holy Spirit has come upon you. You will be witnesses to me in Jerusalem, in all Judea and Samaria, and to the uttermost parts of the earth.”",
      "KJV": "But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me both in Jerusalem, and in all Judaea, and in Samaria, and unto the uttermost part of the earth."
    }
  },
  {
    "id": "romans-6-23",
    "reference": "Romans 6:23",
    "text": {
      "WEB": "For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord.",
      "KJV": "For the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord."
    }
  },
  {
    "id": "1-john-1-9",
    "reference": "1 John 1:9",
    "text": {
      "WEB": "If we confess our sins, he is faithful and righteous to forgive us the sins, and to cleanse us from all unrighteousness.",
      "KJV": "If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness."
    }
  },
  {
    "id": "psalm-121-1-2",
    "reference": "Psalm 121:1-2",
    "text": {
      "WEB": "I will lift up my eyes to the hills. Where does my help come from? My help comes from Yahweh, who made heaven and earth.",
      "KJV": "I will lift up mine eyes unto the hills, from whence cometh my help. My help cometh from the LORD, which made heaven and earth."
    }
  },
  {
    "id": "proverbs-22-6",
    "reference": "Proverbs 22:6",
    "text": {
      "WEB": "Train up a child in the way he should go, and when he is old he will not depart from it.",
      "KJV": "Train up a child in the way he should go: and when he is old, he will not depart from it."
    }
  },
  {
    "id": "ecclesiastes-3-1",
    "reference": "Ecclesiastes 3:1",
    "text": {
      "WEB": "For everything there is a season, and a time for every purpose under heaven:",
      "KJV": "To every thing there is a season, and a time to every purpose under the heaven:"
    }
  },
  {
    "id": "lamentations-3-22-23",
    "reference": "Lamentations 3:22-23",
    "text": {
      "WEB": "It is because of Yahweh’s loving kindnesses that we are not consumed, because his compassion doesn’t fail. They are new every morning. Great is your faithfulness.",
      "KJV": "It is of the LORD’S mercies that we are not consumed, because his compassions fail not. They are new every morning: great is thy faithfulness."
    }
  },
  {
    "id": "zephaniah-3-17",
    "reference": "Zephaniah 3:17",
    "text": {
      "WEB": "Yahweh, your God, is among you, a mighty one who will save. He will rejoice over you with joy. He will calm you in his love. He will rejoice over you with singing.",
      "KJV": "The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy; he will rest in his love, he will joy over thee with singing."
    }
  },
  {
    "id": "malachi-3-10",
    "reference": "Malachi 3:10",
    "text": {
      "WEB": "Bring the whole tithe into the storehouse, that there may be food in my house, and test me now in this,” says Yahweh of Armies, “if I will not open you the windows of heaven, and pour you out a blessing, that there will not be room enough for.",
      "KJV": "Bring ye all the tithes into the storehouse, that there may be meat in mine house, and prove me now herewith, saith the LORD of hosts, if I will not open you the windows of heaven, and pour you out a blessing, that there shall not be room enough to receive it."
    }
  },
  {
    "id": "matthew-7-7",
    "reference": "Matthew 7:7",
    "text": {
      "WEB": "“Ask, and it will be given you. Seek, and you will find. Knock, and it will be opened for you.",
      "KJV": "Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you:"
    }
  },
  {
    "id": "mark-12-30",
    "reference": "Mark 12:30",
    "text": {
      "WEB": "you shall love the Lord your God with all your heart, and with all your soul, and with all your mind, and with all your strength.’ This is the first commandment.",
      "KJV": "And thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind, and with all thy strength: this is the first commandment."
    }
  },
  {
    "id": "luke-6-31",
    "reference": "Luke 6:31",
    "text": {
      "WEB": "“As you would like people to do to you, do exactly so to them.",
      "KJV": "And as ye would that men should do to you, do ye also to them likewise."
    }
  },
  {
    "id": "john-15-5",
    "reference": "John 15:5",
    "text": {
      "WEB": "I am the vine. You are the branches. He who remains in me, and I in him, the same bears much fruit, for apart from me you can do nothing.",
      "KJV": "I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit: for without me ye can do nothing."
    }
  },
  {
    "id": "1-corinthians-13-4-7",
    "reference": "1 Corinthians 13:4-7",
    "text": {
      "WEB": "Love is patient and is kind; love doesn’t envy. Love doesn’t brag, is not proud, doesn’t behave itself inappropriately, doesn’t seek its own way, is not provoked, takes no account of evil; doesn’t rejoice in unrighteousness, but rejoices with the truth; bears all things, believes all things, hopes all things, endures all things.",
      "KJV": "Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not puffed up, Doth not behave itself unseemly, seeketh not her own, is not easily provoked, thinketh no evil; Rejoiceth not in iniquity, but rejoiceth in the truth; Beareth all things, believeth all things, hopeth all things, endureth all things."
    }
  },
  {
    "id": "2-corinthians-12-9",
    "reference": "2 Corinthians 12:9",
    "text": {
      "WEB": "He has said to me, “My grace is sufficient for you, for my power is made perfect in weakness.” Most gladly therefore I will rather glory in my weaknesses, that the power of Christ may rest on me.",
      "KJV": "And he said unto me, My grace is sufficient for thee: for my strength is made perfect in weakness. Most gladly therefore will I rather glory in my infirmities, that the power of Christ may rest upon me."
    }
  },
  {
    "id": "ephesians-6-10-11",
    "reference": "Ephesians 6:10-11",
    "text": {
      "WEB": "Finally, be strong in the Lord, and in the strength of his might. Put on the whole armor of God, that you may be able to stand against the wiles of the devil.",
      "KJV": "Finally, my brethren, be strong in the Lord, and in the power of his might. Put on the whole armour of God, that ye may be able to stand against the wiles of the devil."
    }
  },
  {
    "id": "philippians-1-6",
    "reference": "Philippians 1:6",
    "text": {
      "WEB": "being confident of this very thing, that he who began a good work in you will complete it until the day of Jesus Christ.",
      "KJV": "Being confident of this very thing, that he which hath begun a good work in you will perform it until the day of Jesus Christ:"
    }
  },
  {
    "id": "colossians-3-2",
    "reference": "Colossians 3:2",
    "text": {
      "WEB": "Set your mind on the things that are above, not on the things that are on the earth.",
      "KJV": "Set your affection on things above, not on things on the earth."
    }
  },
  {
    "id": "1-thessalonians-5-16-18",
    "reference": "1 Thessalonians 5:16-18",
    "text": {
      "WEB": "Rejoice always. Pray without ceasing. In everything give thanks, for this is the will of God in Christ Jesus toward you.",
      "KJV": "Rejoice evermore. Pray without ceasing. In every thing give thanks: for this is the will of God in Christ Jesus concerning you."
    }
  },
  {
    "id": "hebrews-4-16",
    "reference": "Hebrews 4:16",
    "text": {
      "WEB": "Let us therefore draw near with boldness to the throne of grace, that we may receive mercy, and may find grace for help in time of need.",
      "KJV": "Let us therefore come boldly unto the throne of grace, that we may obtain mercy, and find grace to help in time of need."
    }
  },
  {
    "id": "james-4-7",
    "reference": "James 4:7",
    "text": {
      "WEB": "Be subject therefore to God. Resist the devil, and he will flee from you.",
      "KJV": "Submit yourselves therefore to God. Resist the devil, and he will flee from you."
    }
  }
];
